version: '3'
services:
  eureka:
    image: edev.kz/microservice-docker-eureka:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  store-catalog-service:
    image: edev.kz/microservice-docker-store-catalog-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://localhost:8761
    depends_on:
      - eureka